import { Geist, Geist_Mono } from "next/font/google";
import { Syne } from 'next/font/google';  // যদি Syne ফন্ট দরকার হয়
import { DM_Sans } from 'next/font/google';  // যদি DM_Sans ফন্ট দরকার হয়
import "./globals.css";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import Services from "@/components/Services";

// ফন্টগুলি ইনিশিয়ালাইজ করা
const syne = Syne({
  variable: "--font-syne",
  subsets: ['latin'],
});

const dmSans = DM_Sans({
  variable: "--font-dmSans",
  subsets: ['latin'],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${syne.variable} ${dmSans.variable} antialiased`}  // তোমার ফন্টগুলিকে একত্রিত করা
      >
        <Navbar/>
        <Hero/>
        <Services/>
        {children}
      </body>
    </html>
  );
}
